=== jouergagner75/bb/cxs-be-security-auth-extension-points/exchange-rate-specification/src/main/resources/schemas/exchange-rate.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "rate": {
      "type": "number",
      "description": "Exchange rate value."
    },
    "source": {
      "type": "string",
      "description": "Source(send) currency code"
    },
    "target": {
      "type": "string",
      "description": "Target(receive) currency code"
    },
    "time": {
      "type": "string",
      "format": "date",
      "description": "Timestamp for exchange rate."
    }
  }
}

=== jouergagner75/bb/dbs-integrating-access-control-to-direct-integration/exchange-rate-specification/src/main/resources/examples/exchange-rates-get.json
[
  {
    "rate": 1.1279,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-13T00:00:00+0000"
  },
  {
    "rate": 1.12504,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-12T00:00:00+0000"
  },
  {
    "rate": 1.12235,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-11T00:00:00+0000"
  },
  {
    "rate": 1.12341,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-10T00:00:00+0000"
  },
  {
    "rate": 1.12341,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-09T00:00:00+0000"
  },
  {
    "rate": 1.11859,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-08T00:00:00+0000"
  },
  {
    "rate": 1.11789,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-07T00:00:00+0000"
  },
  {
    "rate": 1.12911,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-06T00:00:00+0000"
  },
  {
    "rate": 1.1291,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-05T00:00:00+0000"
  },
  {
    "rate": 1.13099,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-04T00:00:00+0000"
  },
  {
    "rate": 1.13638,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-03T00:00:00+0000"
  },
  {
    "rate": 1.13638,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-02T00:00:00+0000"
  },
  {
    "rate": 1.13547,
    "source": "EUR",
    "target": "USD",
    "time": "2019-03-01T00:00:00+0000"
  },
  {
    "rate": 1.13627,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-28T00:00:00+0000"
  },
  {
    "rate": 1.13647,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-27T00:00:00+0000"
  },
  {
    "rate": 1.1347,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-26T00:00:00+0000"
  },
  {
    "rate": 1.13377,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-25T00:00:00+0000"
  },
  {
    "rate": 1.13319,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-24T00:00:00+0000"
  },
  {
    "rate": 1.13319,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-23T00:00:00+0000"
  },
  {
    "rate": 1.1321,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-22T00:00:00+0000"
  },
  {
    "rate": 1.13243,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-21T00:00:00+0000"
  },
  {
    "rate": 1.13276,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-20T00:00:00+0000"
  },
  {
    "rate": 1.1278,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-19T00:00:00+0000"
  },
  {
    "rate": 1.12945,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-18T00:00:00+0000"
  },
  {
    "rate": 1.12411,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-15T00:00:00+0000"
  },
  {
    "rate": 1.12523,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-14T00:00:00+0000"
  },
  {
    "rate": 1.12508,
    "source": "EUR",
    "target": "USD",
    "time": "2019-02-13T00:00:00+0000"
  }
]
